name: test

on:
  pull_request:
    branches:
      - 'main'

env:
  DISTRO: 24.04

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os : [ubuntu-24.04]
        # os : [ ubuntu-24.04, macos-26, macos-26-intel, windows-2025, windows-arm ]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10   #v6.0.3

      - uses: ./.github/actions/setup-python-build
        with:
          python-version: 3.13.11

      # - name: Run PyTest
      #   run: python -m pytest ./tests

      - name: Get Kathara Version
        id: get-version
        run: |
          echo "version=$(cat ./src/Kathara/version.py | grep CURRENT_VERSION | sed -r -e 's/^.*"(.*)"$/\1/g')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Deb Package
        id: cache-deb
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae    #v5.0.5
        with:
          path: ./scripts/Linux-Deb/Output
          key: deb-${{ steps.get-version.outputs.version }}-${{ hashFiles('src/**', 'scripts/Linux-Deb/**') }}
      - name: Build Deb Package
        if: steps.cache-deb.outputs.cache-hit != 'true'
        run: | 
          cd ./scripts/Linux-Deb
          sed -i -e "s|__KATHARA_VERSION__|${{ steps.get-version.outputs.version }}|g" Makefile
          make docker-unsigned_$DISTRO
      
      - name: Cache Pkg Package
        id: cache-pkg
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae    #v5.0.5
        with:
          path: ./scripts/Linux-Pkg/Output
          key: pkg-${{ steps.get-version.outputs.version }}-${{ hashFiles('src/**', 'scripts/Linux-Pkg/**') }}
      - name: Build Pkg Package
        if: steps.cache-pkg.outputs.cache-hit != 'true'
        run: |
          cd ./scripts/Linux-Pkg/
          sed -i -e "s|__KATHARA_VERSION__|${{ steps.get-version.outputs.version }}|g" Makefile
          make clean
          mkdir -p Output && chmod 777 Output
          make docker-build-local

      - name: Cache Rpm Package
        id: cache-rpm
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae    #v5.0.5
        with:
          path: ./scripts/Linux-Rpm/Output
          key: rpm-${{ steps.get-version.outputs.version }}-${{ hashFiles('src/**', 'scripts/Linux-Rpm/**') }}
      - name: Build Rpm Package
        if: steps.cache-rpm.outputs.cache-hit != 'true'
        run: | 
          cd ./scripts/Linux-Rpm
          sed -i -e "s|__KATHARA_VERSION__|${{ steps.get-version.outputs.version }}|g" Makefile
          make all
